create extension if not exists pgcrypto;

create table if not exists app_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique check (length(username) between 3 and 24),
  username_norm text not null unique,
  password_hash text not null,
  balance integer not null default 1000 check (balance >= 0),
  campaign_standard jsonb not null default '{"unlocked":1,"progress":{},"completed":false,"tomUnlocked":false}'::jsonb,
  campaign_hardcore jsonb not null default '{"runActive":true,"unlockedEggs":[],"completed":false}'::jsonb,
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists online_profiles (
  user_id uuid primary key references app_users(id) on delete cascade,
  total_withdrawn bigint not null default 0,
  online_wins integer not null default 0,
  online_rounds integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists match_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references app_users(id) on delete cascade,
  mode text not null,
  opponent text,
  result text not null,
  player_total integer,
  opponent_total integer,
  bet integer not null default 0,
  delta integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists global_chat (
  id bigint generated by default as identity primary key,
  user_id uuid references app_users(id) on delete set null,
  username text not null,
  message text not null check (length(message) between 1 and 200),
  created_at timestamptz not null default now()
);

create table if not exists online_rooms (
  id uuid primary key default gen_random_uuid(),
  room_code text not null unique,
  visibility text not null check (visibility in ('public','private')),
  host_user_id uuid not null references app_users(id) on delete cascade,
  mode text not null check (mode in ('normal','survival','rounds_won')),
  target_rounds integer not null default 5,
  total_rounds integer not null default 5,
  max_players integer not null check (max_players between 1 and 6),
  allow_bots boolean not null default true,
  loan_count integer not null default 3 check (loan_count between 0 and 3),
  initial_balance integer not null default 1000 check (initial_balance > 0),
  status text not null default 'waiting' check (status in ('waiting','started','finished')),
  created_at timestamptz not null default now()
);

create table if not exists online_room_players (
  room_id uuid not null references online_rooms(id) on delete cascade,
  user_id uuid references app_users(id) on delete cascade,
  username text not null,
  is_bot boolean not null default false,
  seat integer not null check (seat between 1 and 6),
  balance integer not null default 1000 check (balance >= 0),
  score integer not null default 0,
  wins integer not null default 0,
  rounds_won integer not null default 0,
  loans_used integer not null default 0,
  alive boolean not null default true,
  primary key (room_id, seat)
);

create table if not exists room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references online_rooms(id) on delete cascade,
  user_id uuid references app_users(id) on delete set null,
  username text not null,
  message text not null check (length(message) between 1 and 200),
  created_at timestamptz not null default now()
);

create table if not exists online_settlements (
  session_id uuid primary key,
  user_id uuid not null references app_users(id) on delete cascade,
  withdrawn integer not null,
  wins integer not null default 0,
  rounds integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace function settle_online_session(p_user_id uuid, p_session_id uuid, p_final_balance integer, p_withdrawn integer, p_wins integer, p_rounds integer)
returns boolean language plpgsql security definer as $$
declare v_inserted integer;
begin
  insert into online_settlements(session_id, user_id, withdrawn, wins, rounds)
  values (p_session_id, p_user_id, greatest(p_withdrawn,0), greatest(p_wins,0), greatest(p_rounds,0))
  on conflict (session_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then return true; end if;
  update app_users set balance = greatest(p_final_balance,0), updated_at = now() where id = p_user_id;
  insert into online_profiles(user_id,total_withdrawn,online_wins,online_rounds)
  values(p_user_id, greatest(p_withdrawn,0), greatest(p_wins,0), greatest(p_rounds,0))
  on conflict(user_id) do update set
    total_withdrawn = online_profiles.total_withdrawn + greatest(p_withdrawn,0),
    online_wins = online_profiles.online_wins + greatest(p_wins,0),
    online_rounds = online_profiles.online_rounds + greatest(p_rounds,0),
    updated_at = now();
  return true;
end; $$;

alter table app_users enable row level security;
alter table online_profiles enable row level security;
alter table match_history enable row level security;
alter table global_chat enable row level security;
alter table online_rooms enable row level security;
alter table online_room_players enable row level security;
alter table room_messages enable row level security;
alter table online_settlements enable row level security;

revoke all on function settle_online_profile(uuid,uuid,integer,integer,integer) from public, anon, authenticated;
grant execute on function settle_online_profile(uuid,uuid,integer,integer,integer) to service_role;
